name: ci

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install deno
        uses: denolib/setup-deno@master

      - name: Run deno
        run: |
          deno --version
          deno run --unstable --allow-net --allow-read --allow-write --import-map=import_map.json mod.ts
